#!/usr/bin/env bash
Transfers a file from our client to a server
variables
path="$(cd "$(dirname "$(BASH_SOURCE[0]}")" >/dev/null 2>61 66 pwd)"
filename=$ (basename "$BASH_SOURCE")
brown-\e[0;33m'
reset-'\033 [0m
file-"41"
ip="62"
user "ubuntu"
key--/.ssh/id_rsa"
if [ -eq 2]; then
scp -i "key" -o StrictHostKeyChecking no "path"/"$file" "user"@"sip":/home/"user"/
else
echo -e "Usage: $(brown)$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY$(reset)"
fi
